CREATE USER KH IDENTIFIED BY KH;
GRANT RESOURCE, CONNECT TO KH;

CREATE USER SCOTT IDENTIFIED BY SCOTT;
GRANT RESOURCE, CONNECT TO SCOTT; 

CREATE USER WORKBOOK IDENTIFIED BY WORKBOOK;
GRANT RESOURCE, CONNECT TO WORKBOOK;

CREATE USER VEGITOR IDENTIFIED BY VEGITOR;
GRANT RESOURCE, CONNECT TO VEGITOR;